//
// Star rating control written in Swift for iOS.
//
// https://github.com/marketplacer/Cosmos
//
// This file was automatically generated by combining multiple Swift source files.
//

import UIKit


struct CosmosTouch {
    static func touchRating(_ locationX: CGFloat, starsWidth: CGFloat, settings: CosmosSettings) -> Double {
        let position = locationX / starsWidth
        let totalStars = Double(settings.totalStars)
        let actualRating = totalStars * Double(position)
        var correctedRating = actualRating
        correctedRating += 0.25
        correctedRating = CosmosRating.displayedRatingFromPreciseRating(correctedRating, totalStars: settings.totalStars)
        correctedRating = max(settings.minTouchRating, correctedRating)
        return correctedRating
    }
}

